june/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin

from tastypie.api import Api

from july import api
from july.forms import PasswordResetForm

v1_api = Api(api_name='v1')
v1_api.register(api.CommitResource())
v1_api.register(api.ProjectResource())
v1_api.register(api.UserResource())
v1_api.register(api.LocationResource())
v1_api.register(api.TeamResource())


admin.autodiscover()


urlpatterns = patterns(
    '',
    # This line should only be active during maintenance!
    # url(r'^.*', 'july.views.maintenance'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^_admin/', admin.site.urls),
    # bitbucket and github are special apis
    url(r'^api/v1/bitbucket$', api.BitbucketHandler.as_view()),
    url(r'^api/v1/github$', api.GithubHandler.as_view()),
    url(r'^api/v1/github/(?P<path>.*)$', api.GithubAPIHandler.as_view()),
    url(r'^api/v1/vegas/$', api.VegasHandler.as_view()),
    # Tasty Pie apis
    url(r'^api/', include(v1_api.urls)),
    url(r'^$', 'july.views.index', name='index'),
    url(r'^live/', 'july.views.live', name='julython-live'),
    url(r'^help/', 'july.views.help_view', name='help'),
    url(r'^signin/$', auth_views.login, name="signin"),
    url(r'^register/$', 'july.views.register', name="register"),
    url(r'^email_verify/(?P<uidb36>[\d\w]+)-(?P<token>[\d\w-]+)$',
        'july.views.email_verify', name='email_verify'),
    url(r'^signout/$', auth_views.logout, {'next_page': '/'}, name="signout"),
    # Password reset urls
    url(r'^password_reset/$', auth_views.password_reset,
        {'password_reset_form': PasswordResetForm},
        name="password_reset"),
    url(r'^password_reset_sent/$', auth_views.password_reset_done,
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': '/password_reset_complete/'},
        name='password_reset_confirm'),
    url(r'^password_reset_complete/$', auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^abuse$', 'july.views.send_abuse', name='abuse'),

    url(r'^accounts/profile', 'july.views.login_redirect'),
    url(r'^accounts/', include('social_auth.urls')),
    url(r'^', include('july.game.urls')),
    url(r'^', include('july.blog.urls')),
    # People urls are greedy, add them last
    url(r'^', include('july.people.urls')),
)

june/people/models.py
import logging
from urlparse import urlparse
from datetime import datetime, timedelta

from django.db import models, transaction
from django.conf import settings
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from jsonfield import JSONField
from django.db.models.aggregates import Sum, Count
from django.utils.timezone import utc, now
from django.utils.html import strip_tags
from django.core.mail import mail_admins
from django.template import loader
import requests


class Commit(models.Model):
    """
    Commit record for the profile, the parent is the profile
    that way we can update the commit count and last commit timestamp
    in the same transaction.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    hash = models.CharField(max_length=255, unique=True)
    author = models.CharField(max_length=255, blank=True)
    name = models.CharField(max_length=255, blank=True)
    email = models.CharField(max_length=255, blank=True)
    message = models.CharField(max_length=2024, blank=True)
    url = models.CharField(max_length=512, blank=True)
    project = models.ForeignKey("Project", blank=True, null=True)
    timestamp = models.DateTimeField(db_index=True)
    created_on = models.DateTimeField(auto_now_add=True)
    files = JSONField(blank=True, null=True)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return u'Commit: %s' % self.hash

    @property
    def languages(self):
        langs = []
        if self.files:
            for f in self.files:
                langs.append(f.get('language'))
        langs = filter(None, langs)
        return set(langs)

    @classmethod
    def create_by_email(cls, email, commits, project=None):
        """Create a commit by email address"""
        return cls.create_by_auth_id(
            'email:%s' % email, commits, project=project)

    @classmethod
    def user_model(cls):
        return cls._meta.get_field('user').rel.to

    @classmethod
    def create_by_auth_id(cls, auth_id, commits, project=None):
        if not isinstance(commits, (list, tuple)):
            commits = [commits]

        user = cls.user_model().get_by_auth_id(auth_id)

        if user:
            return cls.create_by_user(user, commits, project=project)
        return cls.create_orphan(commits, project=project)

    @classmethod
    @transaction.atomic
    def create_by_user(cls, user, commits, project=None):
        """Create a commit with parent user, updating users points."""
        created_commits = []

        if not user.is_active:
            return created_commits

        for c in commits:
            c['user'] = user
            c['project'] = project
            commit_hash = c.pop('hash', None)

            if commit_hash is None:
                logging.info("Commit hash missing in create.")
                continue
            commit, created = cls.objects.get_or_create(
                hash=commit_hash,
                defaults=c)
            if created:
                # increment the counts
                created_commits.append(commit)
            else:
                commit.user = user
                commit.save()

        # Check if there are no new commits and return
        if not created_commits:
            return []

        if project is not None:
            user.projects.add(project)
            user.save()

        # TODO: (Robert Myers) add a call to the defer a task to calculate
        # game stats in a queue?
        return created_commits

    @classmethod
    def create_orphan(cls, commits, project=None):
        """Create a commit with no parent."""
        created_commits = []
        for c in commits:
            c['project'] = project
            commit_hash = c.get('hash')

            if commit_hash is None:
                logging.info("Commit hash missing in create.")
                continue

            commit, created = cls.objects.get_or_create(
                hash=commit_hash,
                defaults=c)
            if created:
                created_commits.append(commit)

        return created_commits

    @classmethod
    def calendar(cls, game, **kwargs):
        """
        Returns number of commits per day for a date range.
        """
        count = cls.objects.filter(
            timestamp__range=(game.start, game.end), **kwargs) \
            .extra(select={'timestamp': 'date(timestamp)'}) \
            .values('timestamp').annotate(commit_count=Count('id'))
        resp = {
            'start': game.start.date(),
            'end': game.end.date(),
            'objects': list(count)
        }
        return resp


class Project(models.Model):
    """
    Project Model:

    This is either a brand new project or an already existing project
    such as #django, #fabric, #tornado, #pip, etc.

    When a user Tweets a url we can automatically create anew project
    for any of the repo host we know already. (github, bitbucket)
    """

    url = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    name = models.CharField(max_length=255, blank=True)
    forked = models.BooleanField(default=False)
    forks = models.IntegerField(default=0)
    watchers = models.IntegerField(default=0)
    parent_url = models.CharField(max_length=255, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    slug = models.SlugField()
    service = models.CharField(max_length=30, blank=True, default='')
    repo_id = models.IntegerField(blank=True, null=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        if self.name:
            return self.name
        else:
            return self.slug

    def save(self, *args, **kwargs):
        self.slug = self.project_name
        super(Project, self).save(*args, **kwargs)

    @property
    def points(self):
        try:
            board = self.board_set.latest()
        except:
            return 0
        return board.points

    @property
    def total(self):
        return self.points

    @property
    def project_name(self):
        return self.parse_project_name(self.url)

    def get_absolute_url(self):
        return reverse('project-details', args=[self.slug])

    @classmethod
    def create(cls, **kwargs):
        """Get or create shortcut."""
        repo_id = kwargs.get('repo_id')
        url = kwargs.get('url')
        slug = cls.parse_project_name(url)
        service = kwargs.get('service')

        # If the repo is on a service with no repo id, we can't handle renames.
        if not repo_id:
            project, created = cls.objects.get_or_create(
                slug=slug, defaults=kwargs)

        # Catch renaming of the repo.
        else:
            defaults = kwargs.copy()
            defaults['slug'] = slug
            project, created = cls.objects.get_or_create(
                service=service, repo_id=repo_id,
                defaults=defaults)
            if created and cls.objects.filter(slug=slug).count() > 1:
                # This is an old project that was created without a repo_id.
                project.delete()  # Delete the duplicate project
                project = cls.objects.get(slug=slug)

        if not project.active:
            # Don't bother updating this project and don't add commits.
            return None

        # Update stale project information.
        project.update(slug, created, **kwargs)
        return project

    @classmethod
    def _get_bitbucket_data(cls, **kwargs):
        """Update info from bitbucket if needed."""
        url = kwargs.get('url', '')
        parsed = urlparse(url)
        if parsed.netloc == 'bitbucket.org':
            # grab data from the bitbucket api
            # TODO: (rmyers) authenticate with oauth?
            api = 'https://bitbucket.org/api/1.0/repositories%s'
            try:
                r = requests.get(api % parsed.path)
                data = r.json()
                kwargs['description'] = data.get('description') or ''
                kwargs['forks'] = data.get('forks_count') or 0
                kwargs['watchers'] = data.get('followers_count') or 0
            except:
                logging.exception("Unable to parse: %s", url)
        return kwargs.iteritems()

    def update(self, slug, created, **kwargs):
        old = (now() - self.updated_on).seconds >= 21600
        if created or old or slug != self.slug:
            for key, value in self._get_bitbucket_data(**kwargs):
                setattr(self, key, value)
            self.slug = slug
            self.save()

    @classmethod
    def parse_project_name(cls, url):
        """
        Parse a project url and return a name for it.

        Example::

            Given:
              http://github.com/julython/julython.org
            Return:
              gh-julython-julython.org

        This is used as the Key name in order to speed lookups during
        api requests.
        """
        if not url:
            return
        hosts_lookup = {
            'github.com': 'gh',
            'bitbucket.org': 'bb',
        }
        parsed = urlparse(url)
        path = parsed.path
        if path.startswith('/'):
            path = path[1:]
        tokens = path.split('/')
        netloc_slug = parsed.netloc.replace('.', '-')
        host_abbr = hosts_lookup.get(parsed.netloc, netloc_slug)
        name = '-'.join(tokens)
        if name.endswith('-'):
            name = name[:-1]
        name = name.replace('.', '_')
        return '%s-%s' % (host_abbr, name)


class Group(models.Model):
    slug = models.SlugField(primary_key=True)
    name = models.CharField(max_length=64, blank=False)
    total = models.IntegerField(default=0)
    approved = models.BooleanField(default=False)
    rel_lookup = None
    lookup = None

    class Meta:

june/templates/july/user_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block bodyclass %}profile{% endblock %}

{% block content %}

<div class="container profile-container section-container no-border">
  <div class="row">
    <div class="span10 offset1">
      <div class="media">
        <a class="thumbnail hidden-phone pull-left avatar" href="{% if 'http' in profile.url %}{{ profile.url }}{% else %}http://{{ profile.url}}{% endif %}" target="_blank">
          {% if profile.picture_url %}
          <img class="media-object" src="{{ profile.picture_url }}" alt="{{profile}}" />
          {% else %}
          <img class="media-object" src="{{ STATIC_URL }}images/spread_the_word_button.png" alt="{{profile}}" />
          {% endif %}
        </a>
        <div class="media-body">
          <h3 class="media-heading">{{ profile }}
            <span class="points pull-right">
            {% firstof profile.total '0' %} {% trans "points" %}
            </span>
          </h3>
          <svg class="hidden-phone" id="commit-calendar"></svg>
          <p class="about-me">{{ profile.description }}</p>
          <ul class="nav nav-pills">
            {% if profile.twitter %}
            <li><a href="https://twitter.com/{% firstof profile.twitter.extra_data.screen_name profile.username %}" class="fa fa-twitter larger" title='{% trans "Twitter" %}'> </a></li>
            {% endif %}
            {% if profile.github %}
            <li><a href="http://github.com/{{ profile.github.uid }}" class="fa fa-github larger" title='{% trans "Github" %}'> </a></li>
            {% endif %}
            {% if profile.gittip %}
            <li><a href="https://www.gittip.com/{{ profile.gittip.uid }}/" class="fa fa-gittip larger" title='{% trans "Gittip" %}'> </a></li>
            {% endif %}
            {% if profile.location %}
            <li><a href="{% url 'location-detail' profile.location.slug %}" class="fa fa-map-marker"> {{ profile.location}}</a></li>
            {% endif %}
            {% if profile.team %}
              {% if profile.team.approved %}
              <li><a href="{% url 'team-details' profile.team.slug %}" class="fa fa-group"> {{ profile.team.name }}</a></li>
              {% else %}
              <li><a href="/help/#team" class="fa fa-group"> {% trans "team waiting approval" %}</a></li>
              {% endif %}
            {% endif %}
          </ul>
        </div>

        {% include "includes/badges.html" %}

        <div class="tabbable">
          <ul class="nav nav-tabs hidden-phone">
            <li class="active">
              <a href="#projects" data-toggle="tab">{% trans "Projects" %}</a>
            </li>
            <li>
              <a href="#commits" data-toggle="tab">{% trans "Commits" %}</a>
            </li>
            {% if profile.username == user.username %}
            <li>
              <a href="#github-projects" data-toggle="tab">{% trans "Github Projects" %}</a>
            </li>
            <li class="pull-right"><a href="{% url 'edit-profile' username=profile.username %}">{% trans "Edit Profile" %}</a></li>
            {% elif request.can_report_abuse and not user.is_superuser %}
            <li id="abuseli" class="pull-right">
              <a href="#abuse-modal" data-toggle="modal">{% trans "Report abuse" %}</a>
            </li>
            {% endif %}
            {% if user.is_superuser %}
            <li class="pull-right">
              <a href="/_admin/july/user/{{ profile.pk }}/">{% trans "Disable User" %}</a>
            </li>
            {% endif %}
          </ul>
          {% url 'edit-profile' username=user.username as edit_profile_url %}
          <div class="tab-content">
            <div class="tab-pane active" id="projects">
              {% include "people/people_projects.html" %}
            </div>
            <div class="tab-pane hidden-phone" id="github-projects">
              {% include "people/github_projects.html" %}
            </div>
            <div class="tab-pane hidden-phone" id="commits">
              <div class="row">
                <div class="span10">
                  {% if profile.commit_set.count %}
                  <div class="row">
                    <div class="span10">
                      <h2 class="spread-the-word">{{ profile }}'s Commits</h2>
                      <div id="commits" data-bind="pageBottom: fetch">
                        <div data-bind="foreach: commits">
                          {% include "includes/commit.html" %}
                        </div>
                        <a class="btn btn-primary" data-bind="click: fetch">Load More</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% else %}
                  {% if profile.username != user.username %}
                  <div class="row">
                    <div class="span10">
                      <h2 class="spread-the-word">{% trans "Still preparing for lift off!" %}</h2>
                      <p class="lead">{% trans "This user has not committed to any project yet." %}</p>
                    </div>
                  </div>
                  {% else %}
                  <div class="row">
                    <div class="span10">
                      <h2 class="spread-the-word">{% trans "Let's get started!" %}</h2>
                      <p class="lead">
                      {% blocktrans %}First <a href="{{ edit_profile_url }}">edit your profile</a> and add all the email addresses you use to commit with.  This is how we'll identify you, we will not display or share this information.{% endblocktrans %}
                      </p>
                    </div>
                  </div>
                  {% include "includes/hook-instructions.html" %}
                  {% endif %}
                {% endif %}
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% include "includes/abuse.html" %}
{% endblock %}

{# Used within blocktrans #}

{% block extra_javascript %}

<script type="text/javascript">
  var view = new JULY.CommitsView({userId: {{ profile.id }}});
  JULY.applyBindings(view, '#commits');
  var projects = new JULY.ProjectsView({userId: {{ profile.id }}});
  JULY.applyBindings(projects, '#project-list');
  var badges = new JULY.BadgesView({userId: {{ profile.id }}});
  JULY.applyBindings(badges, '#badges-list');
  {% if profile.github %}
  var repos = new JULY.RepositoryView({csrf_token: '{{ csrf_token }}'});
  JULY.applyBindings(repos, '#github')
  {% endif %}
  JULY.makeCalendar('#commit-calendar', '{{ profile.username }}');
</script>
{% endblock %}