june/people/urls.py
from django.conf.urls import patterns, url

from july.people import views


urlpatterns = patterns(
    'july.people.views',
    url(r'^(?P<username>[\w.@+-]+)/$',
        views.UserProfile.as_view(),
        name='member-profile'),
    url(r'^(?P<username>[\w.@+-]+)/edit/$',
        'edit_profile', name='edit-profile'),
    url(r'^(?P<username>[\w.@+-]+)/address/$',
        'edit_address', name='edit-address'),
    url(r'^(?P<username>[\w.@+-]+)/email/(?P<email>.*)$',
        'delete_email', name='delete-email'),
    url(r'^(?P<username>[\w.@+-]+)/project/(?P<slug>.*)$',
        'delete_project', name='delete-project'),
    url(r'^(?P<username>[\w.@+-]+)/projects/$',
        'people_projects', name='user-projects'),
)

june/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin

from tastypie.api import Api

from july import api
from july.forms import PasswordResetForm

v1_api = Api(api_name='v1')
v1_api.register(api.CommitResource())
v1_api.register(api.ProjectResource())
v1_api.register(api.UserResource())
v1_api.register(api.LocationResource())
v1_api.register(api.TeamResource())


admin.autodiscover()


urlpatterns = patterns(
    '',
    # This line should only be active during maintenance!
    # url(r'^.*', 'july.views.maintenance'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^_admin/', admin.site.urls),
    # bitbucket and github are special apis
    url(r'^api/v1/bitbucket$', api.BitbucketHandler.as_view()),
    url(r'^api/v1/github$', api.GithubHandler.as_view()),
    url(r'^api/v1/github/(?P<path>.*)$', api.GithubAPIHandler.as_view()),
    url(r'^api/v1/vegas/$', api.VegasHandler.as_view()),
    # Tasty Pie apis
    url(r'^api/', include(v1_api.urls)),
    url(r'^$', 'july.views.index', name='index'),
    url(r'^live/', 'july.views.live', name='julython-live'),
    url(r'^help/', 'july.views.help_view', name='help'),
    url(r'^signin/$', auth_views.login, name="signin"),
    url(r'^register/$', 'july.views.register', name="register"),
    url(r'^email_verify/(?P<uidb36>[\d\w]+)-(?P<token>[\d\w-]+)$',
        'july.views.email_verify', name='email_verify'),
    url(r'^signout/$', auth_views.logout, {'next_page': '/'}, name="signout"),
    # Password reset urls
    url(r'^password_reset/$', auth_views.password_reset,
        {'password_reset_form': PasswordResetForm},
        name="password_reset"),
    url(r'^password_reset_sent/$', auth_views.password_reset_done,
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': '/password_reset_complete/'},
        name='password_reset_confirm'),
    url(r'^password_reset_complete/$', auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^abuse$', 'july.views.send_abuse', name='abuse'),

    url(r'^accounts/profile', 'july.views.login_redirect'),
    url(r'^accounts/', include('social_auth.urls')),
    url(r'^', include('july.game.urls')),
    url(r'^', include('july.blog.urls')),
    # People urls are greedy, add them last
    url(r'^', include('july.people.urls')),
)

june/models.py
"""
Custom User Model for Julython
==============================

This is experimental, but so much worth it!
"""

from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils.crypto import salted_hmac
from social_auth.models import UserSocialAuth

from july.people.models import Location, Team, Project


class User(AbstractUser):
    location = models.ForeignKey(Location, blank=True, null=True,
                                 related_name='location_members')
    team = models.ForeignKey(Team, blank=True, null=True,
                             related_name='team_members')
    projects = models.ManyToManyField(Project, blank=True, null=True)
    description = models.TextField(blank=True)
    url = models.URLField(blank=True, null=True)
    picture_url = models.URLField(blank=True, null=True)

    def __unicode__(self):
        return self.get_full_name() or self.username

    def add_auth_id(self, auth_str):
        """
        Add a social auth identifier for this user.

        The `auth_str` should be in the format '{provider}:{uid}'
        this is useful for adding multiple unique email addresses.

        Example::

            user = User.objects.get(username='foo')
            user.add_auth_id('email:foo@example.com')
        """
        provider, uid = auth_str.split(':')
        return UserSocialAuth.create_social_auth(self, uid, provider)

    def add_auth_email(self, email, request=None):
        """
        Adds a new, non verified email address, and sends a verification email.
        """
        auth_email = self.add_auth_id('email:%s' % email)
        auth_email.extra_data = {'verified': False}
        auth_email.save()
        return auth_email

    def get_provider(self, provider):
        """Return the uid of the provider or None if not set."""
        try:
            return self.social_auth.filter(provider=provider).get()
        except UserSocialAuth.DoesNotExist:
            return None

    def find_valid_email(self, token):
        result = None
        for email_auth in self.social_auth.filter(provider="email"):
            email = email_auth.uid
            expected = salted_hmac(settings.SECRET_KEY, email).hexdigest()
            if expected == token:
                result = email_auth
        return result

    @property
    def gittip(self):
        return self.get_provider('gittip')

    @property
    def twitter(self):
        return self.get_provider('twitter')

    @property
    def github(self):
        return self.get_provider('github')

    @classmethod
    def get_by_auth_id(cls, auth_str):
        """
        Return the user identified by the auth id.

        Example::

            user = User.get_by_auth_id('twitter:julython')
        """
        provider, uid = auth_str.split(':')
        sa = UserSocialAuth.get_social_auth(provider, uid)
        if sa is None:
            return None
        return sa.user

    @property
    def auth_ids(self):
        auths = self.social_auth.all()
        return [':'.join([a.provider, a.uid]) for a in auths]

    @property
    def points(self):
        try:
            player = self.player_set.latest()
        except:
            return 0
        return player.points

    @property
    def total(self):
        return self.points

june/people/views.py
import logging
import json

from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template.context import RequestContext
from django.template.defaultfilters import slugify
from django.views.generic import detail
from django.utils.crypto import salted_hmac
from django.utils.translation import ugettext_lazy as _
from django.utils.http import int_to_base36
from django.utils.html import strip_tags
from django.core.mail import EmailMultiAlternatives, mail_admins
from django.template import loader
from django.contrib.sites.models import get_current_site
from social_auth.models import UserSocialAuth

from july.settings import SECRET_KEY as SECRET
from july.models import User


class UserProfile(detail.DetailView):
    model = User
    slug_field = 'username'
    context_object_name = 'profile'
    slug_url_kwarg = 'username'

    def get_object(self):
        obj = super(UserProfile, self).get_object()
        if not obj.is_active:
            raise Http404("User not found")
        return obj


# TODO (rmyers): move the rest of these views to knockback/backbone routes


def people_projects(request, username):
    return HttpResponseRedirect(reverse('member-profile', args=[username]))


def send_verify_email(email, user_id, domain):
    token = salted_hmac(SECRET, email).hexdigest()
    c = {
        'email': email,
        'domain': domain,
        'uid': int_to_base36(user_id),
        'token': token
    }
    subject = _('Julython - verify your email')
    html = loader.render_to_string(
        'registration/verify_email.html', c)
    text = strip_tags(html)
    msg = EmailMultiAlternatives(subject, text, None, [email])
    msg.attach_alternative(html, 'text/html')
    try:
        msg.send()
    except:
        logging.exception("Unable to send email!")


@login_required
def edit_profile(request, username, template_name='people/edit.html'):
    from forms import EditUserForm
    user = request.user

    if user.username != request.user.username:
        http403 = HttpResponse("This ain't you!")
        http403.status = 403
        return http403

    form = EditUserForm(request.POST or None, user=request.user)

    if form.is_valid():
        for key, value in form.cleaned_data.iteritems():
            if key in ['gittip']:
                continue
            if key in ['email']:
                # send verification email
                domain = get_current_site(request).domain
                if value is not None:
                    send_verify_email(value, user.pk, domain)
                # Don't actually add email to user model.
                continue
            if key == 'team':
                # slugify the team to allow easy lookups
                setattr(user, 'team_slug', slugify(value))
            setattr(user, key, value)
        user.save()

        return HttpResponseRedirect(
            reverse('member-profile', kwargs={'username': user.username}))

    ctx = {
        'form': form,
        'profile': user,
        'active': 'edit',
    }
    return render(request, template_name,
                  ctx, context_instance=RequestContext(request))


@login_required
def edit_address(request, username, template_name='people/edit_address.html'):
    from forms import EditAddressForm

    user = request.user

    if user.key != request.user.key:
        http403 = HttpResponse("This ain't you!")
        http403.status = 403
        return http403

    form = EditAddressForm(request.POST or None, user=user)

    if form.is_valid():
        for key, value in form.cleaned_data.iteritems():
            setattr(user, key, value)
            user.put()
        return HttpResponseRedirect(
            reverse('member-profile', kwargs={'username': user.username})
        )

    ctx = {
        'form': form,
        'profile': user,
        'active': 'edit',
    }
    return render(request, template_name, ctx,
                  context_instance=RequestContext(request))


@login_required
def delete_email(request, username, email):

    # the ID we are to delete
    user = User.objects.get(username=username)
    auth = UserSocialAuth.objects.get(provider="email", uid=email)
    e_user = auth.user

    if user is None or e_user is None:
        raise Http404("User not found")

    if user != request.user or user != e_user:
        http403 = HttpResponse("This ain't you!")
        http403.status = 403
        return http403

    if request.method == "POST":
        # delete the email from the user
        auth.delete()
        return HttpResponseRedirect(
            reverse('member-profile',
                    kwargs={'username': request.user.username})
        )

    return render_to_response(
        'people/delete_email.html',
        {'email': email},
        context_instance=RequestContext(request)
    )


@login_required
def delete_project(request, username, slug):

    try:
        project = request.user.projects.get(slug=slug)
    except:
        raise Http404("Project Not Found")

    if request.method == "POST":
        # delete the project from the user
        request.user.projects.remove(project)
        request.user.save()
        return HttpResponseRedirect(
            reverse('member-profile',
                    kwargs={'username': request.user.username})
        )

    return render_to_response(
        'people/delete_project.html',
        {'project': project},
        context_instance=RequestContext(request)
    )

june/templates/people/delete_email.html
{% extends "base.html" %}

{% load i18n %}

{% block bodyclass %}profile{% endblock %}

{% block content %} 
<div class="container section-container no-border" id="contents">
  <div class="row">
  <div class="span8 offset2">
    <h2 class="what-is-this">{% trans "Remove Email?" %}</h2>
      <form method="post" action="{% url 'delete-email' user.username email %}" enctype="multipart/form-data">{% csrf_token %}
        <div class="well">
           <p class="lead">{% trans "Are you sure you want to delete this email:" %}</p>
           <p>{{ email }}</p>
        </div>
        <div class="form-actions">
          <input type="submit" class="btn btn-primary" value="{% trans "Yes Delete" %}" />
          <a href="{% url 'edit-profile' user.username %}" class="btn">{% trans "Cancel" %}</a>
        </div>   
      </form>
    </div>
  </div>
</div>
{% endblock %}

june/templates/people/delete_project.html
{% extends "base.html" %}

{% load i18n %}

{% block bodyclass %}profile{% endblock %}

{% block content %} 
<div class="container section-container no-border" id="contents">
  <div class="row">
    <div class="span8 offset2">
      <h2 class="what-is-this">{% trans "Remove Project?" %}</h2>
      <form method="post" 
        action="{% url 'delete-project' user.username project.slug %}" 
        enctype="multipart/form-data">
        {% csrf_token %}
        <div class="well">
           <p class="lead">{% trans "Are you sure you want to remove this project?" %}</p>
           <p>{{ project }}</p>
        </div>
        <div class="form-actions">
          <input type="submit" class="btn btn-primary" value="{% trans "Yes Delete" %}" />
          <a href="{% url 'member-profile' user.username %}" class="btn">{% trans "Cancel" %}</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

june/templates/people/edit.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<div class="container" id="contents">
    <div class="row">
        <div class="span8 offset2">
            <h1 class="user">{% block formtitle %}{% trans "Edit Profile" %}{%  endblock %}</h1>
            <form method="post" action="." enctype="multipart/form-data">{% csrf_token %}
                <div class="well">
                {% for field in form %}
                <div class="control-group{% if field.errors %} error{% endif %}">
                    <span>{{ field.label_tag }}</span> {%  if not field.field.required %}<em>(optional)</em>{% endif %}
                    <div class="controls">
                        {{ field }}
                        {% if field.errors %}<span class="help-inline">{% for e in field.errors %}{{ e }} {% endfor %}</span>{% endif %}
                    </div>
                </div>
                {% endfor %}
                {% if form.emails %}
                <div class="control-group{% if field.errors %} error{% endif %}">
                    <label>{% trans "Existing emails" %}</label>
                    <div class="controls">
                        <ul>
                            {% for email in form.emails %}
                            <li>{{ email.uid }} <a href="{% url 'delete-email' user.username email.uid %}" class="delete">{% trans "delete" %}</a>
                                {% if email.extra_data.verified %}
                                    [{% trans "verified" %}]
                                {% else %}
                                    [{% trans "unverified" %}]
                                {% endif %}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% endif %}
                <div class="control-group">
                    <label>{% trans "OAuth Accounts" %}</label>
                    <div class="controls">
                    <ul>
                        <li>{% trans "Twitter: " %}{% if form.twitter %}
                            {% firstof form.twitter.extra_data.screen_name form.twitter.uid %}{% else %}
                            <a class="signin btn btn-info" href="/accounts/login/twitter/"><i class="icon-user icon-white"></i> Link Twitter Account</a>{% endif %}</li>
                        <li>{% trans "Github: " %}{% if form.github %}{{ form.github.uid }}{% else %}
                            <a class="signin btn btn-info" href="/accounts/login/github/"><i class="icon-user icon-white"></i> Link Github Account</a>{% endif %}</li>
                    </ul>
                    </div>
                </div>
                <div class="form-actions">
                    <input type="submit" class="btn btn-primary" value="{% trans "Save" %}" />
                    <a href=".." class="btn">{% trans "Cancel" %}</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script>
  var profile = new JULY.ProfileView();
  JULY.applyBindings(profile, "#contents");
  JULY.makeCalendar('#commit-calendar', '{{ profile.username }}');
</script>
{% endblock %}

june/templates/people/edit_address.html
{% extends "people/edit.html" %}
{% block formtitle %}What's Your Address?{% endblock %}

june/templates/people/github_projects.html
{% load i18n %}
<div id="project-list">
  {% if profile.username == user.username %}
  <div class="span6" id="github">
    <h2 class="teaming-up">{% trans "Github Projects" %}</h2>
    {% if not profile.github %}
    <a class="signin btn btn-info" href="/accounts/login/github/">
      <i class="icon-user icon-white"></i> Link Github Account</a>
    {% else %}
    <p data-bind="visible: repos().length == 0">{% blocktrans %}BETA: Add hooks to your projects on github! Click 'Fetch Projects' to load your projects.{% endblocktrans %}</p>
    <div data-bind="foreach: repos">
      <div class="well well-small">
        <img src="{{ STATIC_URL }}images/loader.gif" data-bind="visible: working" style="display: none;" />
        <div data-bind="if: !working()">
          <h4>
            <a data-bind="text: name, attr: {href: html_url}" target="_blank"></a>
          </h4>
          <p data-bind="text: description"></p>
          <a data-bind="click: add.bind($data, '{{ csrf_token }}'), visible: hooks().length == 0" class="btn btn-info">
            {% trans "Add Hook" %}
          </a>
          <div data-bind="foreach: hooks">
            <span class="label" data-bind="text: last_response.status, css: {'label-success': last_response.code == 200}"></span> <span data-bind="timeago: updated_at"></span>
            <a data-bind="click: test.bind($data, '{{ csrf_token }}')">{% trans "Test" %}</a>
          </div>
        </div>
      </div>
    </div>
    <a  data-bind="click: fetch" class="btn btn-info">Fetch Projects</a>
    {% endif %}
  </div>
  {% endif %}
</div>

june/templates/people/language_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block bodyclass %}profile{% endblock %}

{% block content %}

<div class="container section-container no-border">
    <div class="row locations">
        <div class="span10 offset1"><br />
            <div class="row project">
            <div class="span6">
              <a href="{% url 'languages' %}">{% trans "All languages" %}</a>
              <h3>{{ language }}</h3>
            </div>
          </div>
          <div class="row">
            <div class="span10">
            <h2 class="spread-the-word">{% trans "Commits" %}</h2>
              <div id="commits" data-bind="pageBottom: fetch">
              	<div data-bind="foreach: commits">
              		<div class="media">
	            	  <a class="thumbnail pull-left" data-bind="visible: picture_url, attr: {href: '/' + username() +'/'}">
		            	<img class="media-object" data-bind="attr: {src: picture_url, alt: username}" />
	            	  </a>
	            	  <div class="media-body">
	            	  	<h4 class="media-heading" data-bind="timeago: timestamp"></h4>
	            		<strong data-bind="text: message"></strong>
	            		<p class="hash">
	                      	<a data-bind="visible: username, text: username, attr: {href: '/' + username() + '/' }"></a> <span data-bind="visible: username, text: '&mdash;'"></span>
	                      	<a data-bind="visible: url, attr:{href:url }"><span data-bind="text: hash().substring(0, 8)"></span></a>
	                      	<span data-bind="visible: !url(), text: hash().substring(0, 8)"></span>
	                      </p>
	              	  </div>
	                </div>
              	</div>
              	<a class="btn btn-primary" data-bind="visible: hasMore, click: fetch">Load More</a>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

{% endblock %}
{% block extra_javascript %}
<script type="text/javascript">
	var view = new JULY.CommitsView({languages: ['{{ language.name }}'] });
	JULY.applyBindings(view, '#commits');
</script>
{% endblock %}

june/templates/people/location_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}

<div class="container-fluid leaderboard">
    <div class="row-fluid">
      <div class="span10 offset1">
        <h2 class="teaming-up">Location &mdash; {{ location }} 
          <span class="pull-right">{{ location.total_points }} {% trans "points" %}</h2>
      </div>
    </div>
    <div class="row-fluid">
        <div class="span5 offset1">
          <h4>{% trans "People" %}</h4>
            {% for player in location.members_by_points|slice:":100" %}
              {% include "includes/person.html" %}
            {% endfor %}
        </div> 
        <div class="span5">
          <h4>{% trans "Projects" %}</h4>
            {% for board in location.game_boards|slice:":100" %}
              {% include "includes/board.html" %}
            {% endfor %}  
        </div>
        </div>
    </div>
</div>

{% endblock %}

june/templates/people/location_list.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<div class="container section-container no-border">
  <div class="row locations">
    <div class="span8 offset2">
        <h2 class="teaming-up">{% trans "Locations" %}</h2>
        {% for location in object_list|slice:":100" %}
          <div class="row location">
            <div class="span5">
              <h3><a href="{% url 'location-detail' location.slug %}">{{ location }}</a></h3>
            </div>
            <div class="points pull-right">
                <p>{{ location.total }}</p>
                <p class="small">{% trans "points" %}</p>
            </div>
          </div>
        {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

june/templates/people/people_projects.html
{% load i18n %}
<div id="project-list">
  <div data-bind="visible: projects().length > 0">
      <h2 class="spread-the-word">{% trans "Projects" %}</h2>
      {% if profile.username == user.username %}
        <p class="lead">{% blocktrans %}Link more projects under the 'Github Projects' tabs or add the <a href="/help/#webhook">hook manually</a>{% endblocktrans %}</p>
      {% endif %}
      <div data-bind="foreach: projects" class="projects">
        {% include "includes/user_project.html" %}
      </div>
  </div>
  <div data-bind="visible: projects().length == 0">
    <h2 class="spread-the-word">{% trans "Let's get started!" %}</h2>
    <p class="lead">
    {% blocktrans %}First <a href="{{ edit_profile_url }}">edit your profile</a> and add all the email addresses you use to commit with.  This is how we'll identify you, we will not display or share this information.{% endblocktrans %}
    </p>
    {% include "includes/hook-instructions.html" %}
  </div>
</div>

june/templates/people/project_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block bodyclass %}profile{% endblock %}

{% block content %}

<div class="container profile-container">
  <div class="row">
    <div class="span10 offset1">
      <div class="media">
        <a class="thumbnail pull-left avatar" href=".">
          <img class="media-object" src="{{ STATIC_URL }}/images/participating_button.png" alt="{{project}}" />
        </a>
        <div class="media-body">
          <h2 class="media-heading">{{ project }}
            <small class="stats">
              {% trans "Watchers" %}: {{ project.watchers }}
              {% trans "Forks" %}: {{ project.forks }}
            </small>
            <small class="points pull-right">
              {% firstof project.total '0' %} {% trans "points" %}
            </small>
          </h2>
          {# <svg id="commit-calendar"></svg> #}
          <p class="about-me">{{ project.description }}</p>
          <ul class="nav nav-pills">
            <li><a href="{{ project.url }}"><i class="icon-globe"></i> {{ project.url }}</a></li>
          </ul>
        </div>
        <div class="tabbable"> <!-- Only required for left/right tabs -->
          <ul class="nav nav-tabs">
            <li class="active"><a href="#players" data-toggle="tab">{% trans "Players" %}</a></li>
            <li><a href="#commits" data-toggle="tab">{% trans "Commits" %}</a></li>
            {% if request.can_report_abuse and not user.is_superuser %}
            <li id="abuseli" class="pull-right">
              <a href="#abuse-modal" data-toggle="modal">{% trans "Report abuse" %}</a>
            </li>
            {% endif %}
            {% if user.is_superuser %}
            <li class="pull-right">
              <a href="/_admin/people/project/{{ project.pk }}/">{% trans "Disable Project" %}</a>
            </li>
          {% endif %}
          </ul>
          <div class="tab-content">
            <div class="tab-pane active" id="players">
              <div class="row">
                <div class="span6">   
                <h4>{% trans "Players" %}</h4>
                <ul>
                  {% for user in project.user_set.all|slice:":100" %}
                    <li>
                      <a href="{% url 'member-profile' user.username %}">{{ user }}</a> &mdash;
                        {% blocktrans count number_of_points=user.points %}{{ number_of_points }} point in {% plural %}{{ number_of_points }} points in {% endblocktrans %}
                        {% blocktrans count number_of_projects=user.projects.count %}{{ number_of_projects }} project{% plural %}{{ number_of_projects }} projects{% endblocktrans %}
                    </li>
                  {% endfor %}  
                </ul>
                </div>
          </div>
            </div>
            <div class="tab-pane" id="commits">
              <div class="row">
                <div class="span10">   
                <h2>{% trans "Commits" %}</h2>
                  <div id="commits" data-bind="pageBottom: fetch">
                    <div data-bind="foreach: commits">
                      {% include "includes/commit.html" %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% include "includes/abuse.html" %}
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript">
	var view = new JULY.CommitsView({projectId: {{ project.id }}});
	JULY.applyBindings(view, '#commits');
</script>
{% endblock %}

june/templates/people/team_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}

<div class="container-fluid leaderboard">
    <div class="row-fluid">
      <div class="span10 offset1">
        <h2 class="teaming-up">Team &mdash; {{ team }} 
          <span class="pull-right">{{ team.total_points }} {% trans "points" %}</h2>
      </div>
    </div>
    <div class="row-fluid">
        <div class="span5 offset1">
          <h4>{% trans "People" %}</h4>
            {% for player in team.members_by_points|slice:":100" %}
              {% include "includes/person.html" %}
            {% endfor %}
        </div> 
        <div class="span5">
          <h4>{% trans "Projects" %}</h4>
            {% for board in team.game_boards|slice:":100" %}
              {% include "includes/board.html" %}
            {% endfor %}  
        </div>
        </div>
    </div>
</div>

{% endblock %}

june/templates/people/team_list.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<div class="container section-container no-border">
  <div class="row locations">
    <div class="span8 offset2">
        <h2 class="teaming-up">{% trans "Teams" %}</h2>
        {% for team in object_list %}
          <div class="row location">
            <div class="span5">
              <h3><a href="{% url 'team-details' team.slug %}">{{ team }}</a></h3>
            </div>
            <div class="points pull-right">
                <p>{{ team.total }}</p>
                <p class="small">{% trans "points" %}</p>
            </div>
          </div>
        {% endfor %}
    </div>
  </div>
</div>

{% endblock %}